# Generated by Django 4.2.7 on 2023-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('img', models.ImageField(max_length=255, upload_to='заявки/')),
                ('time_mark', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('новая', 'Новая'), ('в_работе', 'Принято в работу'), ('выполнено', 'Выполнено')], default='новая', max_length=100)),
            ],
        ),
    ]
