# Generated by Django 4.2.6 on 2023-11-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(help_text='Описание заявки'),
        ),
    ]
