# Generated by Django 4.2.7 on 2023-11-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_application_user_alter_application_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='img',
        ),
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
