# Generated by Django 4.2.6 on 2023-11-19 08:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_application_img_application_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(max_length=2097152, upload_to='images', validators=[main.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Новая'), ('B', 'Принято в работу'), ('C', 'Выполнено')], default='A', max_length=20),
        ),
    ]
