# Generated by Django 4.2.6 on 2023-11-19 08:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_application_image_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='images', validators=[main.models.validate_image_extension]),
        ),
    ]
