# Generated by Django 4.2.6 on 2023-11-19 08:45

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_application_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(max_length=2097152, upload_to='images', validators=[main.models.validate_image_extension]),
        ),
    ]
